### ISSUE TITLE
`npm run clean` and `npm run clean:all` returns various errors

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#11]
In trying to QA d56b84b79656b8b0483a858881a8ca83ed56ca8d, I first tried to run a `npm run clean` and `npm run clean:all`.

Both commands result in errors, but the errors seem to differ.

### `npm run clean`

```
npm run clean
...
webpack built a4263e35f09fc642fb1c in 11977ms
webpack 5.90.3 compiled successfully
```
Seems to hang after "compiled successfully".

### `npm run clean:all`

```
npm run clean:all

> meme-boilerplate@1.3.0 clean:all
> node meme clean --all

PATH         -- codebase located at: /Users/loh/dev/meme-2023/src
PATH         -- meme root folder located at: /Users/loh/dev/meme-2023
UR_EXPRESS   - COMPILING WEBSERVER w/ WEBPACK - THIS MAY TAKE SEVERAL SECONDS...
WEBPACK      - ... using webpack.base.config
WEBPACK      - ... using webpack.webapp.config
MEME EXEC    - removing dist/, data/, and built/ directories...
MEME EXEC    - directories removed!
MEME EXEC    - also removing node_modules/
MEME EXEC    - you will have to reinstall them with the
MEME EXEC    - npm ci command.
MEME EXEC    - operation complete!
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module './hash/md4'
Require stack:
- /Users/loh/dev/meme-2023/node_modules/webpack/lib/util/createHash.js
- /Users/loh/dev/meme-2023/node_modules/webpack/lib/serialization/ObjectMiddleware.js
- /Users/loh/dev/meme-2023/node_modules/webpack/lib/util/serialization.js
- /Users/loh/dev/meme-2023/node_modules/webpack/lib/util/makeSerializable.js
- /Users/loh/dev/meme-2023/node_modules/webpack/lib/WebpackError.js
- /Users/loh/dev/meme-2023/node_modules/webpack/lib/DefinePlugin.js
- /Users/loh/dev/meme-2023/node_modules/webpack/lib/index.js
- /Users/loh/dev/meme-2023/src/config/webpack.webapp.config.js
- /Users/loh/dev/meme-2023/src/system/server-express.js
- /Users/loh/dev/meme-2023/src/system/server.js
- /Users/loh/dev/meme-2023/meme.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at module.exports (/Users/loh/dev/meme-2023/node_modules/webpack/lib/util/createHash.js:169:17)
    at /Users/loh/dev/meme-2023/node_modules/webpack/lib/DefinePlugin.js:349:22
    at Hook.eval [as call] (eval at create (/Users/loh/dev/meme-2023/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/loh/dev/meme-2023/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/loh/dev/meme-2023/node_modules/webpack/lib/Compiler.js:1139:26)
    at /Users/loh/dev/meme-2023/node_modules/webpack/lib/Compiler.js:1183:29 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/loh/dev/meme-2023/node_modules/webpack/lib/util/createHash.js',
    '/Users/loh/dev/meme-2023/node_modules/webpack/lib/serialization/ObjectMiddleware.js',
    '/Users/loh/dev/meme-2023/node_modules/webpack/lib/util/serialization.js',
    '/Users/loh/dev/meme-2023/node_modules/webpack/lib/util/makeSerializable.js',
    '/Users/loh/dev/meme-2023/node_modules/webpack/lib/WebpackError.js',
    '/Users/loh/dev/meme-2023/node_modules/webpack/lib/DefinePlugin.js',
    '/Users/loh/dev/meme-2023/node_modules/webpack/lib/index.js',
    '/Users/loh/dev/meme-2023/src/config/webpack.webapp.config.js',
    '/Users/loh/dev/meme-2023/src/system/server-express.js',
    '/Users/loh/dev/meme-2023/src/system/server.js',
    '/Users/loh/dev/meme-2023/meme.js'
  ]
}

Node.js v18.20.2
```

**Comment by benloh** [comment]
@Sakelun I think there might be some errors related to webpack changes when we try to do `npm run clean` and `npm run clean:all`.
Can you guys take a look at that please?

**Comment by Sakelun** [comment]
@benloh claimfixed in #14 

I've tested this issue and all of the scripts: `start`, `dev`, `package`, `clean`, and `clean:all`. The root cause was the insertion of an extra `Start()` statement in one of the core scripts that was likely introduced as a debug measure but kept by mistake.

**Comment by benloh** [comment]
@Sakelun Thanks!  Yes, it's helpful to flag this and assign it back to me.  I'll test it when we merge the PR.

**Comment by benloh** [comment]
Confirmed fixed!  Thanks!
